# Algorithm Settings
cpu: 8
steps_per_epoch: 120000
epochs: 2000
with_state: true
zero_state: false
gcn: true
hidden_dim: 128
random: true

seed: 5

# Environment Settings
max_cycle: 100
map_size: 96
step_reward: -0.05
dead_penalty: -0.5
attack_penalty: -0.1
attack_food_reward: 1.0
communication_range: 2
min_neigh: 1
message_size: 5
view_range: 6
vae_model: true
global_reward: false

vae_observation_dim: 96
hid_shape: 160
latent_state_shape: 128
