# Algorithm Settings
gamma: 0.995
seed: 0
cpu: 8
steps_per_epoch: 32000
epochs: 500
hidden_dim: 128

# Environment Settings
max_cycle: 120
map_size: 40
step_reward: -0.005
dead_penalty: -1.0
attack_penalty: -0.01
attack_opponent_reward: 0.5
enemy_policy: 'ppo'
communication_range: 2
plot_topology: False
