# Algorithm Settings
gamma: 0.995
seed: 0
cpu: 1
steps: 8000
epochs: 500
hidden_dim: 128

# Environment Settings
max_cycle: 120
map_size: 16
step_reward: -0.005
dead_penalty: -0.1
attack_penalty: -0
attack_opponent_reward: 0.5
