batch_size: 128
n_episode: 100000
n_epoch: 5
capacity: 100000

vae_model: true
max_cycle: 80
map_size: 40
step_reward: -0.05
dead_penalty: -0.5
attack_penalty: -0.1
attack_food_reward: 1.0

with_state: false
zero_state: false

vae_observation_dim: 96