# Algorithm Settings
cpu: 1
steps_per_epoch: 120000
epochs: 500

# Environment Settings
max_cycle: 120
map_size: 40
step_reward: -0.005
dead_penalty: -1.0
attack_penalty: -0.05
attack_food_reward: 0.5
enemy_policy: 'ppo'
communication_range: 2
message_size: 5
view_range: 6
