# Algorithm Settings
cpu: 8
steps_per_epoch: 120000
epochs: 500
centralized: False

# Environment Settings
max_cycle: 120
map_size: 20
step_reward: -0.05
dead_penalty: -0.5
attack_penalty: -0.1
attack_food_reward: 1.0
communication_range: 2
message_size: 5
view_range: 6
vae_observation_dim: 96
vae_model: True