# Algorithm Settings
cpu: 1
steps_per_epoch: 5000
epochs: 2000
centralized: false
with_state: true
zero_state: false
gcn: true

# Environment Settings
max_cycle: 80
map_size: 40
step_reward: -0.05
dead_penalty: -0.5
attack_penalty: -0.1
attack_food_reward: 1.0
communication_range: 2
message_size: 5
view_range: 6
vae_model: true

vae_observation_dim: 96
hid_shape: 160
latent_state_shape: 128
