batch_size: 128
n_episode: 200000
n_epoch: 5
capacity: 10000
update_interval: 200

vae_model: true
max_cycle: 100
map_size: 48
view_range: 6
step_reward: -0.05
dead_penalty: -0.5
attack_penalty: -0.1
attack_food_reward: 1.0

with_state: false
zero_state: false
global_reward: false

vae_observation_dim: 96
hidden_dim: 128
save_interval: 20
random_episode: 20