batch_size: 512
n_episode: 15000
n_epoch: 20
capacity: 20000
tau: 0.005
action_net: true
mfq: true
random: false

seed: 5

vae_model: true
max_cycle: 100
map_size: 96
view_range: 6
step_reward: -0.05
dead_penalty: -0.5
attack_penalty: -0.1
attack_food_reward: 1.0

gcn: false
with_state: false
zero_state: false
global_reward: false

vae_observation_dim: 96
hidden_dim: 128
save_interval: 50
random_episode: 50
hid_shape: 160
latent_state_shape: 128
